config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'home#index'
  mount Sidekiq::Web => '/sidekiq'

  resources :images
  resources :users, except: [:index]

  get 'health' => 'home#health'
  get 'zone' => 'home#zone'
  get 'version' => 'home#version'
  get 'dbinfo' => 'home#dbinfo'
  post 'start_unhealthy' => 'home#start_unhealthy'
  post 'start_healthy' => 'home#start_healthy'
  post 'start_load' => 'home#start_load'
  post 'start_failover' => 'home#start_failover'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user

  has_one_attached :picture
end

app/models/user.rb
class User < ApplicationRecord
  has_many :images, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token, if: -> { request.format.json? }

  def health
    if Redis.new.get('unhealthy_status').present?
      head 500
    else
      render plain: 'OK', status: :ok
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :fetch_zone, only: [:index, :zone]
  before_action :fetch_template, only: [:index, :version]
  before_action :fetch_dbzone, only: [:index, :dbinfo]
  before_action :fetch_dbstatus, only: [:index, :dbinfo]

  def index
    @hostname = %x{ hostname }
    @version = ENV['APP_VERSION']
    @current_load = $REDIS.get('load_status').present? ? 'HIGH' : 'NORMAL'
    @health_check = $REDIS.get('unhealthy_status').present? ? 'UNHEALTHY' : 'HEALTHY'
  end

  def zone
    render plain: "app zone: #{@zone}"
  end

  def version
    render plain: "app version: #{ENV['APP_VERSION']}\ntemplate: #{@template}\n"
  end

  def dbinfo
    render plain: "database zone: #{@dbzone}\nstatus: #{@dbstatus}\n"
  end

  def start_healthy
    $REDIS.del('unhealthy_status')
    redirect_to root_path
  end

  def start_unhealthy
    $REDIS.set('unhealthy_status', true)
    redirect_to root_path
  end

  def start_load
    SimulateHighCpuLoadJob.perform_later
    $REDIS.set('load_status', true)
    redirect_to root_path
  end

  def start_failover
    SimulateDatabaseFailoverJob.perform_later
    redirect_to root_path
  end

  private

  def fetch_zone
    cmd = "gcloud compute instance-groups managed list-instances #{ENV['GCLOUD_MIGS_NAME']} --region #{ENV['GCLOUD_MIGS_REGION']} --filter=\"NAME:$(hostname)\" --format=\"table(ZONE)\""
    @zone = `#{cmd}`.split("\n").last rescue 'command not found'
  end

  def fetch_template
    cmd = "gcloud compute instance-groups managed list-instances #{ENV['GCLOUD_MIGS_NAME']} --region #{ENV['GCLOUD_MIGS_REGION']} --filter=\"NAME:$(hostname)\" --format=\"table(INSTANCE_TEMPLATE)\""
    @template = `#{cmd}`.split("\n").last rescue 'command not found'
  end

  def fetch_dbzone
    cmd = "gcloud sql instances list --filter=\"NAME:#{ENV['GCLOUD_SQL_NAME']}\" --format=\"table(LOCATION)\""
    @dbzone = `#{cmd}`.split("\n").last rescue 'command not found'
  end

  def fetch_dbstatus
    cmd = "gcloud sql instances list --filter=\"NAME:#{ENV['GCLOUD_SQL_NAME']}\" --format=\"table(STATUS)\""
    @dbstatus = `#{cmd}`.split("\n").last rescue 'command not found'
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]
  before_action :load_user_list, except: [:index, :show, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.includes(:user)
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.includes(:user).find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def image_params
      params.require(:image).permit(:user_id, :title, :picture)
    end

    def load_user_list
      @users = User.select(:id, :name).map { |user| [user.name, user.id] }
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.includes(:images).find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<table class="table table-hover table-striped">
  <caption>Table of MIGs App Status</caption>
  <tbody>
    <tr>
      <td><strong>Hostname</strong></td>
      <td><%= @hostname %></td>
    </tr>
    <tr>
      <td><strong>Zone</strong></td>
      <td><%= @zone %></td>
    </tr>
    <tr>
      <td><strong>Template</strong></td>
      <td><%= @template %></td>
    </tr>
    <tr>
      <td><strong>Version</strong></td>
      <td><%= @version %></td>
    </tr>
    <tr>
      <td><strong>Current Load</strong></td>
      <td><span class="badge badge-pill badge-<%= @current_load == 'HIGH' ? 'danger' : 'success' %>"><%= @current_load %></span></td>
    </tr>
    <tr>
      <td><strong>Health Check</strong></td>
      <td><span class="badge badge-pill badge-<%= @health_check == 'UNHEALTHY' ? 'danger' : 'success' %>"><%= @health_check %></span></td>
    </tr>
    <tr>
      <td><strong>Database Zone</strong></td>
      <td><%= @dbzone %></td>
    </tr>
    <tr>
      <td><strong>Database Status</strong></td>
      <td><span class="badge badge-pill badge-<%= @dbstatus == 'MAINTENANCE' ? 'danger' : 'success' %>"><%= @dbstatus %></span></td>
    </tr>
    <tr>
      <td><strong>Actions Button</strong></td>
      <td>
        <% if @health_check == 'UNHEALTHY' %>
          <%= link_to 'Make Healthy', start_healthy_path, method: :post, class: 'btn btn-primary my-1' %>
        <% else %>
          <%= link_to 'Make Unhealty', start_unhealthy_path, method: :post, class: 'btn btn-primary my-1' %>
        <% end %>
        <%= link_to 'Start Load', start_load_path, method: :post, class: 'btn btn-primary my-1' %>
        <%= link_to 'Start Failover', start_failover_path, method: :post, class: 'btn btn-primary my-1' %>
      </td>
    </tr>
    <tr>
      <td><strong>Actions URL</strong></td>
      <td>
        <%= link_to 'Health Check URL', health_path, class: 'btn btn-primary my-1', target: '_blank' %>
        <%= link_to 'Version URL', version_path, class: 'btn btn-primary my-1', target: '_blank' %>
        <%= link_to 'Zone URL', zone_path, class: 'btn btn-primary my-1', target: '_blank' %>
        <%= link_to 'Database Info URL', dbinfo_path, class: 'btn btn-primary my-1', target: '_blank' %>
        <%= link_to 'App URL', images_path, class: 'btn btn-primary my-1', target: '_blank' %>
      </td>
    </tr>
  </tbody>
</table>

app/views/images/_form.html.erb
<%= form_with(model: image, local: true) do |form| %>
  <% if image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
        <% image.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :user_id %>
    <%= form.select :user_id, options_for_select(@users), {}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :picture %>
    <%= form.file_field :picture, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="display-3">
  Images
  <div class="float-right">
    <%= link_to 'New User', new_user_path, class: 'btn btn-primary' %>
    <%= link_to 'New Image', new_image_path, class: 'btn btn-secondary' %>
  </div>
</h1>

<div class="row">
  <% @images.each do |image| %>
    <div class="col-3 text-center mb-3">
      <%= link_to image_path(image) do %>
        <%= image_tag image.picture.presence || 'https://dummyimage.com/600x400/000/fff', class: 'img-responsive img-thumbnail' %>
      <% end %>
      <p class="mb-0"><strong><%= image.title %></strong></p>
      <small>by: <%= link_to image.user.name, user_path(image.user) %></small>
    </div>
  <% end %>
</div>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag @image.picture.presence || 'https://dummyimage.com/600x400/000/fff', class: 'img-responsive img-thumbnail' %>
</p>

<p>
  <strong>Title:</strong>
  <%= @image.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @image.user.name %>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %> |
<%= link_to 'Delete', image_path(@image), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MigsAppSample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  </head>

  <body>
    <div class="container mt-5">
      <div class="row">
        <div class="col-12">
          <%= yield %>
        </div>
      </div>
    </div>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', images_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', images_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', images_path %> |
<%= link_to 'Delete', user_path(@user), method: :delete %>